/**
 * Environmental Data Retrieval API\'s
 * Example of Candidate Environmental Data Retrieval API OpenAPI docs
 *
 * The version of the OpenAPI document: 0.0.10
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CollectionDataQueriesPosition } from './collectionDataQueriesPosition';


/**
 * Detailed information relevant to individual query types
 */
export interface CollectionDataQueries { 
    position?: CollectionDataQueriesPosition;
    radius?: CollectionDataQueriesPosition;
    area?: CollectionDataQueriesPosition;
    cube?: CollectionDataQueriesPosition;
    trajectory?: CollectionDataQueriesPosition;
    corridor?: CollectionDataQueriesPosition;
    locations?: CollectionDataQueriesPosition;
    items?: CollectionDataQueriesPosition;
}

