/**
 * Environmental Data Retrieval API\'s
 * Example of Candidate Environmental Data Retrieval API OpenAPI docs
 *
 * The version of the OpenAPI document: 0.0.10
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Parameter } from './parameter';
import { DomainDescription } from './domainDescription';


/**
 * A geospatial coverage interchange format based on JavaScript Object Notation (JSON)
 */
export interface CoverageJSON { 
    /**
     * Coverage domain type
     */
    type: CoverageJSON.TypeEnum;
    domain: DomainDescription;
    parameters: { [key: string]: Parameter; };
    ranges: { [key: string]: object; };
}
export namespace CoverageJSON {
    export type TypeEnum = 'Coverage' | 'CoverageCollection' | 'Domain';
    export const TypeEnum = {
        Coverage: 'Coverage' as TypeEnum,
        CoverageCollection: 'CoverageCollection' as TypeEnum,
        Domain: 'Domain' as TypeEnum
    };
}


