/**
 * Environmental Data Retrieval API\'s
 * Example of Candidate Environmental Data Retrieval API OpenAPI docs
 *
 * The version of the OpenAPI document: 0.0.10
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CrsObject } from './crsObject';
import { DataQueryCoords } from './dataQueryCoords';


/**
 * Property to contain any extra metadata information that is specific to an individual data queries
 */
export interface DataQuery { 
    /**
     * title of the query
     */
    title?: string;
    /**
     * description of the query
     */
    description?: string;
    /**
     * Type of EDR query
     */
    query_type?: DataQuery.QueryTypeEnum;
    coords?: DataQueryCoords;
    /**
     * list of distance units radius values can be specified in
     */
    within_units?: Array<string>;
    /**
     * list of width distance units distance values can be specified in
     */
    width_units?: Array<string>;
    /**
     * list of height distance units distance values can be specified in
     */
    height_units?: Array<string>;
    /**
     * list of formats the results can be presented in
     */
    output_formats?: Array<string>;
    /**
     * default outputformat
     */
    default_output_format?: string;
    /**
     * List of key/value definitions for the CRS\'s supported by a query.  The key is the query parameter and the value is the Well Known Text description
     */
    crs_details?: Array<CrsObject>;
}
export namespace DataQuery {
    export type QueryTypeEnum = 'position' | 'radius' | 'area' | 'cube' | 'trajectory' | 'corridor' | 'items' | 'locations' | 'instances';
    export const QueryTypeEnum = {
        Position: 'position' as QueryTypeEnum,
        Radius: 'radius' as QueryTypeEnum,
        Area: 'area' as QueryTypeEnum,
        Cube: 'cube' as QueryTypeEnum,
        Trajectory: 'trajectory' as QueryTypeEnum,
        Corridor: 'corridor' as QueryTypeEnum,
        Items: 'items' as QueryTypeEnum,
        Locations: 'locations' as QueryTypeEnum,
        Instances: 'instances' as QueryTypeEnum
    };
}


