/**
 * Daraa
 * This data store is offered by CubeWerx Inc. as a demonstration of its in-progress OGC API implementation.
 *
 * The version of the OpenAPI document: 9.3.52
 * Contact: mgalluch@cubewerx.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { LinkJson } from './linkJson';
import { ExtentJson } from './extentJson';


/**
 * This schema defines the JSON metadata resource returned from the /collections/{collectionId} endpoint.
 */
export interface CollectionInfoJson { 
    /**
     * The identifier of the collection.
     */
    id: string;
    /**
     * A human readable title of the collection.
     */
    title?: string;
    /**
     * A description of the members of the collection.
     */
    description?: string;
    links: Array<LinkJson>;
    extent?: ExtentJson;
    /**
     * An indicator about the type of the items in the collection.
     */
    itemType?: string;
    /**
     * The coordinate reference system that may be used to retrieve features from this collection without the need to apply a CRS transformation.
     */
    storageCrs?: string;
    /**
     * The list of coordinate reference systems supported by the API.  The first item is the default coordinate reference system.
     */
    crs?: Array<string>;
}

