/**
 * Daraa
 * This data store is offered by CubeWerx Inc. as a demonstration of its in-progress OGC API implementation.
 *
 * The version of the OpenAPI document: 9.3.52
 * Contact: mgalluch@cubewerx.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * This schema defines the JSON resource returned from the /conformance endpoint.
 */
export interface ConformanceJson { 
    /**
     * An array of URLs, where each URL corresponds to a defined OGC Conformance class.  Unrecognized URLs should be ignored.
     */
    conformsTo: Array<string>;
}

