export * from './collections.service';
import { CollectionsService } from './collections.service';
export * from './conformanceClasses.service';
import { ConformanceClassesService } from './conformanceClasses.service';
export * from './coverages.service';
import { CoveragesService } from './coverages.service';
export * from './dataTiles.service';
import { DataTilesService } from './dataTiles.service';
export * from './landingPage.service';
import { LandingPageService } from './landingPage.service';
export * from './mapTiles.service';
import { MapTilesService } from './mapTiles.service';
export * from './maps.service';
import { MapsService } from './maps.service';
export * from './schemas.service';
import { SchemasService } from './schemas.service';
export * from './sourceImages.service';
import { SourceImagesService } from './sourceImages.service';
export * from './tileMatrixSets.service';
import { TileMatrixSetsService } from './tileMatrixSets.service';
export * from './vectorFeaturesAndCatalogueRecords.service';
import { VectorFeaturesAndCatalogueRecordsService } from './vectorFeaturesAndCatalogueRecords.service';
export const APIS = [CollectionsService, ConformanceClassesService, CoveragesService, DataTilesService, LandingPageService, MapTilesService, MapsService, SchemasService, SourceImagesService, TileMatrixSetsService, VectorFeaturesAndCatalogueRecordsService];
