/**
 * Daraa
 * This data store is offered by CubeWerx Inc. as a demonstration of its in-progress OGC API implementation.
 *
 * The version of the OpenAPI document: 9.3.52
 * Contact: mgalluch@cubewerx.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional }                      from '@angular/core';
import { HttpClient, HttpHeaders, HttpParams,
         HttpResponse, HttpEvent, HttpParameterCodec }       from '@angular/common/http';
import { CustomHttpParameterCodec }                          from '../encoder';
import { Observable }                                        from 'rxjs';


import { BASE_PATH, COLLECTION_FORMATS }                     from '../variables';
import { Configuration }                                     from '../configuration';



@Injectable({
  providedIn: 'root'
})
export class DataTilesService {

    protected basePath = 'https://test.cubewerx.com/cubewerx/cubeserv/demo/ogcapi/Daraa';
    public defaultHeaders = new HttpHeaders();
    public configuration = new Configuration();
    public encoder: HttpParameterCodec;

    constructor(protected httpClient: HttpClient, @Optional()@Inject(BASE_PATH) basePath: string, @Optional() configuration: Configuration) {
        if (configuration) {
            this.configuration = configuration;
        }
        if (typeof this.configuration.basePath !== 'string') {
            if (typeof basePath !== 'string') {
                basePath = this.basePath;
            }
            this.configuration.basePath = basePath;
        }
        this.encoder = this.configuration.encoder || new CustomHttpParameterCodec();
    }


    private addToHttpParams(httpParams: HttpParams, value: any, key?: string): HttpParams {
        if (typeof value === "object" && value instanceof Date === false) {
            httpParams = this.addToHttpParamsRecursive(httpParams, value);
        } else {
            httpParams = this.addToHttpParamsRecursive(httpParams, value, key);
        }
        return httpParams;
    }

    private addToHttpParamsRecursive(httpParams: HttpParams, value?: any, key?: string): HttpParams {
        if (value == null) {
            return httpParams;
        }

        if (typeof value === "object") {
            if (Array.isArray(value)) {
                (value as any[]).forEach( elem => httpParams = this.addToHttpParamsRecursive(httpParams, elem, key));
            } else if (value instanceof Date) {
                if (key != null) {
                    httpParams = httpParams.append(key,
                        (value as Date).toISOString().substr(0, 10));
                } else {
                   throw Error("key may not be null if value is Date");
                }
            } else {
                Object.keys(value).forEach( k => httpParams = this.addToHttpParamsRecursive(
                    httpParams, value[k], key != null ? `${key}.${k}` : k));
            }
        } else if (key != null) {
            httpParams = httpParams.append(key, value);
        } else {
            throw Error("key may not be null if value is not object or array");
        }
        return httpParams;
    }

    /**
     * A metadata document describing the coverage tilesets that are available for the specified collection.
     * @param collectionId The identifier of a collection in this data store.
     * @param f A token indicating the content type to return.  Overrides the HTTP \&quot;Accept\&quot; header if present.
     * @param pretty Whether or not the output should be pretty-formatted (with whitespace, etc.).
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public collectionsCollectionIdCoverageTilesGet(collectionId: 'AgricultureSrf' | 'CulturePnt' | 'CultureSrf' | 'Daraa_DTED' | 'Daraa_mosaic_2019' | 'FacilityPnt' | 'HydrographyCrv' | 'HydrographySrf' | 'MilitarySrf' | 'SettlementSrf' | 'StructurePnt' | 'TransportationGroundCrv' | 'UtilityInfrastructureCrv' | 'UtilityInfrastructurePnt' | 'VegetationSrf', f?: 'json' | 'html', pretty?: boolean, observe?: 'body', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json' | 'text/html' | 'application/problem+json' | 'text/xml'}): Observable<any>;
    public collectionsCollectionIdCoverageTilesGet(collectionId: 'AgricultureSrf' | 'CulturePnt' | 'CultureSrf' | 'Daraa_DTED' | 'Daraa_mosaic_2019' | 'FacilityPnt' | 'HydrographyCrv' | 'HydrographySrf' | 'MilitarySrf' | 'SettlementSrf' | 'StructurePnt' | 'TransportationGroundCrv' | 'UtilityInfrastructureCrv' | 'UtilityInfrastructurePnt' | 'VegetationSrf', f?: 'json' | 'html', pretty?: boolean, observe?: 'response', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json' | 'text/html' | 'application/problem+json' | 'text/xml'}): Observable<HttpResponse<any>>;
    public collectionsCollectionIdCoverageTilesGet(collectionId: 'AgricultureSrf' | 'CulturePnt' | 'CultureSrf' | 'Daraa_DTED' | 'Daraa_mosaic_2019' | 'FacilityPnt' | 'HydrographyCrv' | 'HydrographySrf' | 'MilitarySrf' | 'SettlementSrf' | 'StructurePnt' | 'TransportationGroundCrv' | 'UtilityInfrastructureCrv' | 'UtilityInfrastructurePnt' | 'VegetationSrf', f?: 'json' | 'html', pretty?: boolean, observe?: 'events', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json' | 'text/html' | 'application/problem+json' | 'text/xml'}): Observable<HttpEvent<any>>;
    public collectionsCollectionIdCoverageTilesGet(collectionId: 'AgricultureSrf' | 'CulturePnt' | 'CultureSrf' | 'Daraa_DTED' | 'Daraa_mosaic_2019' | 'FacilityPnt' | 'HydrographyCrv' | 'HydrographySrf' | 'MilitarySrf' | 'SettlementSrf' | 'StructurePnt' | 'TransportationGroundCrv' | 'UtilityInfrastructureCrv' | 'UtilityInfrastructurePnt' | 'VegetationSrf', f?: 'json' | 'html', pretty?: boolean, observe: any = 'body', reportProgress: boolean = false, options?: {httpHeaderAccept?: 'application/json' | 'text/html' | 'application/problem+json' | 'text/xml'}): Observable<any> {
        if (collectionId === null || collectionId === undefined) {
            throw new Error('Required parameter collectionId was null or undefined when calling collectionsCollectionIdCoverageTilesGet.');
        }

        let queryParameters = new HttpParams({encoder: this.encoder});
        if (f !== undefined && f !== null) {
          queryParameters = this.addToHttpParams(queryParameters,
            <any>f, 'f');
        }
        if (pretty !== undefined && pretty !== null) {
          queryParameters = this.addToHttpParams(queryParameters,
            <any>pretty, 'pretty');
        }

        let headers = this.defaultHeaders;

        let credential: string | undefined;
        // authentication (cwApiKeyHeader) required
        credential = this.configuration.lookupCredential('cwApiKeyHeader');
        if (credential) {
            headers = headers.set('CubeWerx-API-Key', credential);
        }

        // authentication (cwApiKeyQuery) required
        credential = this.configuration.lookupCredential('cwApiKeyQuery');
        if (credential) {
            queryParameters = queryParameters.set('apiKey', credential);
        }

        // authentication (cwAuth) required
        credential = this.configuration.lookupCredential('cwAuth');
        if (credential) {
        }

        // authentication (httpBearer) required
        credential = this.configuration.lookupCredential('httpBearer');
        if (credential) {
        }

        // authentication (oauth2) required
        credential = this.configuration.lookupCredential('oauth2');
        if (credential) {
            headers = headers.set('Authorization', 'Bearer ' + credential);
        }

        // authentication (oauth2) required
        credential = this.configuration.lookupCredential('oauth2');
        if (credential) {
            headers = headers.set('Authorization', 'Bearer ' + credential);
        }

        // authentication (oauth2) required
        credential = this.configuration.lookupCredential('oauth2');
        if (credential) {
            headers = headers.set('Authorization', 'Bearer ' + credential);
        }

        let httpHeaderAcceptSelected: string | undefined = options && options.httpHeaderAccept;
        if (httpHeaderAcceptSelected === undefined) {
            // to determine the Accept header
            const httpHeaderAccepts: string[] = [
                'application/json',
                'text/html',
                'application/problem+json',
                'text/xml'
            ];
            httpHeaderAcceptSelected = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        }
        if (httpHeaderAcceptSelected !== undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }


        let responseType: 'text' | 'json' = 'json';
        if(httpHeaderAcceptSelected && httpHeaderAcceptSelected.startsWith('text')) {
            responseType = 'text';
        }

        return this.httpClient.get<any>(`${this.configuration.basePath}/collections/${encodeURIComponent(String(collectionId))}/coverage/tiles`,
            {
                params: queryParameters,
                responseType: <any>responseType,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * A metadata document describing the coverage tiles that are available for the specified collection in the specified tile-matrix set.
     * @param collectionId The identifier of a collection in this data store.
     * @param tileMatrixSetId The identifier of a tile-matrix set that this collection is available in.
     * @param f A token indicating the content type to return.  Overrides the HTTP \&quot;Accept\&quot; header if present.
     * @param pretty Whether or not the output should be pretty-formatted (with whitespace, etc.).
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public collectionsCollectionIdCoverageTilesTileMatrixSetIdGet(collectionId: 'AgricultureSrf' | 'CulturePnt' | 'CultureSrf' | 'Daraa_DTED' | 'Daraa_mosaic_2019' | 'FacilityPnt' | 'HydrographyCrv' | 'HydrographySrf' | 'MilitarySrf' | 'SettlementSrf' | 'StructurePnt' | 'TransportationGroundCrv' | 'UtilityInfrastructureCrv' | 'UtilityInfrastructurePnt' | 'VegetationSrf', tileMatrixSetId: 'wgs84' | '3395' | 'smerc', f?: 'json' | 'html', pretty?: boolean, observe?: 'body', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json' | 'text/html' | 'application/problem+json' | 'text/xml'}): Observable<any>;
    public collectionsCollectionIdCoverageTilesTileMatrixSetIdGet(collectionId: 'AgricultureSrf' | 'CulturePnt' | 'CultureSrf' | 'Daraa_DTED' | 'Daraa_mosaic_2019' | 'FacilityPnt' | 'HydrographyCrv' | 'HydrographySrf' | 'MilitarySrf' | 'SettlementSrf' | 'StructurePnt' | 'TransportationGroundCrv' | 'UtilityInfrastructureCrv' | 'UtilityInfrastructurePnt' | 'VegetationSrf', tileMatrixSetId: 'wgs84' | '3395' | 'smerc', f?: 'json' | 'html', pretty?: boolean, observe?: 'response', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json' | 'text/html' | 'application/problem+json' | 'text/xml'}): Observable<HttpResponse<any>>;
    public collectionsCollectionIdCoverageTilesTileMatrixSetIdGet(collectionId: 'AgricultureSrf' | 'CulturePnt' | 'CultureSrf' | 'Daraa_DTED' | 'Daraa_mosaic_2019' | 'FacilityPnt' | 'HydrographyCrv' | 'HydrographySrf' | 'MilitarySrf' | 'SettlementSrf' | 'StructurePnt' | 'TransportationGroundCrv' | 'UtilityInfrastructureCrv' | 'UtilityInfrastructurePnt' | 'VegetationSrf', tileMatrixSetId: 'wgs84' | '3395' | 'smerc', f?: 'json' | 'html', pretty?: boolean, observe?: 'events', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json' | 'text/html' | 'application/problem+json' | 'text/xml'}): Observable<HttpEvent<any>>;
    public collectionsCollectionIdCoverageTilesTileMatrixSetIdGet(collectionId: 'AgricultureSrf' | 'CulturePnt' | 'CultureSrf' | 'Daraa_DTED' | 'Daraa_mosaic_2019' | 'FacilityPnt' | 'HydrographyCrv' | 'HydrographySrf' | 'MilitarySrf' | 'SettlementSrf' | 'StructurePnt' | 'TransportationGroundCrv' | 'UtilityInfrastructureCrv' | 'UtilityInfrastructurePnt' | 'VegetationSrf', tileMatrixSetId: 'wgs84' | '3395' | 'smerc', f?: 'json' | 'html', pretty?: boolean, observe: any = 'body', reportProgress: boolean = false, options?: {httpHeaderAccept?: 'application/json' | 'text/html' | 'application/problem+json' | 'text/xml'}): Observable<any> {
        if (collectionId === null || collectionId === undefined) {
            throw new Error('Required parameter collectionId was null or undefined when calling collectionsCollectionIdCoverageTilesTileMatrixSetIdGet.');
        }
        if (tileMatrixSetId === null || tileMatrixSetId === undefined) {
            throw new Error('Required parameter tileMatrixSetId was null or undefined when calling collectionsCollectionIdCoverageTilesTileMatrixSetIdGet.');
        }

        let queryParameters = new HttpParams({encoder: this.encoder});
        if (f !== undefined && f !== null) {
          queryParameters = this.addToHttpParams(queryParameters,
            <any>f, 'f');
        }
        if (pretty !== undefined && pretty !== null) {
          queryParameters = this.addToHttpParams(queryParameters,
            <any>pretty, 'pretty');
        }

        let headers = this.defaultHeaders;

        let credential: string | undefined;
        // authentication (cwApiKeyHeader) required
        credential = this.configuration.lookupCredential('cwApiKeyHeader');
        if (credential) {
            headers = headers.set('CubeWerx-API-Key', credential);
        }

        // authentication (cwApiKeyQuery) required
        credential = this.configuration.lookupCredential('cwApiKeyQuery');
        if (credential) {
            queryParameters = queryParameters.set('apiKey', credential);
        }

        // authentication (cwAuth) required
        credential = this.configuration.lookupCredential('cwAuth');
        if (credential) {
        }

        // authentication (httpBearer) required
        credential = this.configuration.lookupCredential('httpBearer');
        if (credential) {
        }

        // authentication (oauth2) required
        credential = this.configuration.lookupCredential('oauth2');
        if (credential) {
            headers = headers.set('Authorization', 'Bearer ' + credential);
        }

        // authentication (oauth2) required
        credential = this.configuration.lookupCredential('oauth2');
        if (credential) {
            headers = headers.set('Authorization', 'Bearer ' + credential);
        }

        // authentication (oauth2) required
        credential = this.configuration.lookupCredential('oauth2');
        if (credential) {
            headers = headers.set('Authorization', 'Bearer ' + credential);
        }

        let httpHeaderAcceptSelected: string | undefined = options && options.httpHeaderAccept;
        if (httpHeaderAcceptSelected === undefined) {
            // to determine the Accept header
            const httpHeaderAccepts: string[] = [
                'application/json',
                'text/html',
                'application/problem+json',
                'text/xml'
            ];
            httpHeaderAcceptSelected = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        }
        if (httpHeaderAcceptSelected !== undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }


        let responseType: 'text' | 'json' = 'json';
        if(httpHeaderAcceptSelected && httpHeaderAcceptSelected.startsWith('text')) {
            responseType = 'text';
        }

        return this.httpClient.get<any>(`${this.configuration.basePath}/collections/${encodeURIComponent(String(collectionId))}/coverage/tiles/${encodeURIComponent(String(tileMatrixSetId))}`,
            {
                params: queryParameters,
                responseType: <any>responseType,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * A coverage tile of the specified collection.
     * @param collectionId The identifier of a collection in this data store.
     * @param tileMatrixSetId The identifier of a tile-matrix set that this collection is available in.
     * @param tileMatrix The identifier of a tile matrix (typically a zoom level) within the specified tile-matrix set.
     * @param tileRow The zero-based row index of the tile in the specified tile matrix.
     * @param tileCol The zero-based column index of the tile in the specified tile matrix.
     * @param datetime Either a date-time or an interval, open or closed. Date and time expressions adhere to RFC 3339.  Open intervals are expressed using double-dots.  Examples:  * A date-time: \&quot;2018-02-12T23:20:50Z\&quot; * A closed interval: \&quot;2018-02-12T00:00:00Z/2018-03-18T12:31:12Z\&quot; * Open intervals: \&quot;2018-02-12T00:00:00Z/..\&quot; or \&quot;../2018-03-18T12:31:12Z\&quot;  Only elements that have a temporal property that intersects the value of &#x60;datetime&#x60; are selected.
     * @param f A token indicating the content type to return.  Overrides the HTTP \&quot;Accept\&quot; header if present.  A value of \&quot;wkb\&quot; (content type \&quot;application/x-cubewerx-wkb\&quot;) indicates CubeWerx\&#39;s raster extension to the Well-Known-Binary format.  \&quot;mvt\&quot; and \&quot;geojson\&quot; can only be requested for feature collections, and \&quot;tiff\&quot; and \&quot;wkb\&quot; can only be requested for coverage collections.
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public collectionsCollectionIdCoverageTilesTileMatrixSetIdTileMatrixTileRowTileColGet(collectionId: 'AgricultureSrf' | 'CulturePnt' | 'CultureSrf' | 'Daraa_DTED' | 'Daraa_mosaic_2019' | 'FacilityPnt' | 'HydrographyCrv' | 'HydrographySrf' | 'MilitarySrf' | 'SettlementSrf' | 'StructurePnt' | 'TransportationGroundCrv' | 'UtilityInfrastructureCrv' | 'UtilityInfrastructurePnt' | 'VegetationSrf', tileMatrixSetId: 'wgs84' | '3395' | 'smerc', tileMatrix: string, tileRow: number, tileCol: number, datetime?: string, f?: 'mvt' | 'geojson' | 'tiff' | 'wkb', observe?: 'body', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/vnd.mapbox-vector-tile' | 'application/geo+json' | 'image/tiff' | 'application/x-cubewerx-wkb' | 'application/problem+json' | 'text/xml' | 'text/html' | 'application/json'}): Observable<any>;
    public collectionsCollectionIdCoverageTilesTileMatrixSetIdTileMatrixTileRowTileColGet(collectionId: 'AgricultureSrf' | 'CulturePnt' | 'CultureSrf' | 'Daraa_DTED' | 'Daraa_mosaic_2019' | 'FacilityPnt' | 'HydrographyCrv' | 'HydrographySrf' | 'MilitarySrf' | 'SettlementSrf' | 'StructurePnt' | 'TransportationGroundCrv' | 'UtilityInfrastructureCrv' | 'UtilityInfrastructurePnt' | 'VegetationSrf', tileMatrixSetId: 'wgs84' | '3395' | 'smerc', tileMatrix: string, tileRow: number, tileCol: number, datetime?: string, f?: 'mvt' | 'geojson' | 'tiff' | 'wkb', observe?: 'response', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/vnd.mapbox-vector-tile' | 'application/geo+json' | 'image/tiff' | 'application/x-cubewerx-wkb' | 'application/problem+json' | 'text/xml' | 'text/html' | 'application/json'}): Observable<HttpResponse<any>>;
    public collectionsCollectionIdCoverageTilesTileMatrixSetIdTileMatrixTileRowTileColGet(collectionId: 'AgricultureSrf' | 'CulturePnt' | 'CultureSrf' | 'Daraa_DTED' | 'Daraa_mosaic_2019' | 'FacilityPnt' | 'HydrographyCrv' | 'HydrographySrf' | 'MilitarySrf' | 'SettlementSrf' | 'StructurePnt' | 'TransportationGroundCrv' | 'UtilityInfrastructureCrv' | 'UtilityInfrastructurePnt' | 'VegetationSrf', tileMatrixSetId: 'wgs84' | '3395' | 'smerc', tileMatrix: string, tileRow: number, tileCol: number, datetime?: string, f?: 'mvt' | 'geojson' | 'tiff' | 'wkb', observe?: 'events', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/vnd.mapbox-vector-tile' | 'application/geo+json' | 'image/tiff' | 'application/x-cubewerx-wkb' | 'application/problem+json' | 'text/xml' | 'text/html' | 'application/json'}): Observable<HttpEvent<any>>;
    public collectionsCollectionIdCoverageTilesTileMatrixSetIdTileMatrixTileRowTileColGet(collectionId: 'AgricultureSrf' | 'CulturePnt' | 'CultureSrf' | 'Daraa_DTED' | 'Daraa_mosaic_2019' | 'FacilityPnt' | 'HydrographyCrv' | 'HydrographySrf' | 'MilitarySrf' | 'SettlementSrf' | 'StructurePnt' | 'TransportationGroundCrv' | 'UtilityInfrastructureCrv' | 'UtilityInfrastructurePnt' | 'VegetationSrf', tileMatrixSetId: 'wgs84' | '3395' | 'smerc', tileMatrix: string, tileRow: number, tileCol: number, datetime?: string, f?: 'mvt' | 'geojson' | 'tiff' | 'wkb', observe: any = 'body', reportProgress: boolean = false, options?: {httpHeaderAccept?: 'application/vnd.mapbox-vector-tile' | 'application/geo+json' | 'image/tiff' | 'application/x-cubewerx-wkb' | 'application/problem+json' | 'text/xml' | 'text/html' | 'application/json'}): Observable<any> {
        if (collectionId === null || collectionId === undefined) {
            throw new Error('Required parameter collectionId was null or undefined when calling collectionsCollectionIdCoverageTilesTileMatrixSetIdTileMatrixTileRowTileColGet.');
        }
        if (tileMatrixSetId === null || tileMatrixSetId === undefined) {
            throw new Error('Required parameter tileMatrixSetId was null or undefined when calling collectionsCollectionIdCoverageTilesTileMatrixSetIdTileMatrixTileRowTileColGet.');
        }
        if (tileMatrix === null || tileMatrix === undefined) {
            throw new Error('Required parameter tileMatrix was null or undefined when calling collectionsCollectionIdCoverageTilesTileMatrixSetIdTileMatrixTileRowTileColGet.');
        }
        if (tileRow === null || tileRow === undefined) {
            throw new Error('Required parameter tileRow was null or undefined when calling collectionsCollectionIdCoverageTilesTileMatrixSetIdTileMatrixTileRowTileColGet.');
        }
        if (tileCol === null || tileCol === undefined) {
            throw new Error('Required parameter tileCol was null or undefined when calling collectionsCollectionIdCoverageTilesTileMatrixSetIdTileMatrixTileRowTileColGet.');
        }

        let queryParameters = new HttpParams({encoder: this.encoder});
        if (datetime !== undefined && datetime !== null) {
          queryParameters = this.addToHttpParams(queryParameters,
            <any>datetime, 'datetime');
        }
        if (f !== undefined && f !== null) {
          queryParameters = this.addToHttpParams(queryParameters,
            <any>f, 'f');
        }

        let headers = this.defaultHeaders;

        let credential: string | undefined;
        // authentication (cwApiKeyHeader) required
        credential = this.configuration.lookupCredential('cwApiKeyHeader');
        if (credential) {
            headers = headers.set('CubeWerx-API-Key', credential);
        }

        // authentication (cwApiKeyQuery) required
        credential = this.configuration.lookupCredential('cwApiKeyQuery');
        if (credential) {
            queryParameters = queryParameters.set('apiKey', credential);
        }

        // authentication (cwAuth) required
        credential = this.configuration.lookupCredential('cwAuth');
        if (credential) {
        }

        // authentication (httpBearer) required
        credential = this.configuration.lookupCredential('httpBearer');
        if (credential) {
        }

        // authentication (oauth2) required
        credential = this.configuration.lookupCredential('oauth2');
        if (credential) {
            headers = headers.set('Authorization', 'Bearer ' + credential);
        }

        // authentication (oauth2) required
        credential = this.configuration.lookupCredential('oauth2');
        if (credential) {
            headers = headers.set('Authorization', 'Bearer ' + credential);
        }

        // authentication (oauth2) required
        credential = this.configuration.lookupCredential('oauth2');
        if (credential) {
            headers = headers.set('Authorization', 'Bearer ' + credential);
        }

        let httpHeaderAcceptSelected: string | undefined = options && options.httpHeaderAccept;
        if (httpHeaderAcceptSelected === undefined) {
            // to determine the Accept header
            const httpHeaderAccepts: string[] = [
                'application/vnd.mapbox-vector-tile',
                'application/geo+json',
                'image/tiff',
                'application/x-cubewerx-wkb',
                'application/problem+json',
                'text/xml',
                'text/html',
                'application/json'
            ];
            httpHeaderAcceptSelected = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        }
        if (httpHeaderAcceptSelected !== undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }


        let responseType: 'text' | 'json' = 'json';
        if(httpHeaderAcceptSelected && httpHeaderAcceptSelected.startsWith('text')) {
            responseType = 'text';
        }

        return this.httpClient.get<any>(`${this.configuration.basePath}/collections/${encodeURIComponent(String(collectionId))}/coverage/tiles/${encodeURIComponent(String(tileMatrixSetId))}/${encodeURIComponent(String(tileMatrix))}/${encodeURIComponent(String(tileRow))}/${encodeURIComponent(String(tileCol))}`,
            {
                params: queryParameters,
                responseType: <any>responseType,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * A metadata document describing the data tilesets that are available for the specified collection, filtered by the scale rules and conditions of the specified style.
     * @param collectionId The identifier of a collection in this data store.
     * @param styleId The identifier of a style in this data store that\&#39;s compatible with the specified collection.
     * @param f A token indicating the content type to return.  Overrides the HTTP \&quot;Accept\&quot; header if present.
     * @param pretty Whether or not the output should be pretty-formatted (with whitespace, etc.).
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public collectionsCollectionIdStylesStyleIdTilesGet(collectionId: 'AgricultureSrf' | 'CulturePnt' | 'CultureSrf' | 'FacilityPnt' | 'HydrographyCrv' | 'HydrographySrf' | 'MilitarySrf' | 'SettlementSrf' | 'StructurePnt' | 'TransportationGroundCrv' | 'UtilityInfrastructureCrv' | 'UtilityInfrastructurePnt' | 'VegetationSrf', styleId: 'Topographic' | 'Overlay' | 'Night' | 'default', f?: 'json' | 'html', pretty?: boolean, observe?: 'body', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json' | 'text/html' | 'application/problem+json' | 'text/xml'}): Observable<any>;
    public collectionsCollectionIdStylesStyleIdTilesGet(collectionId: 'AgricultureSrf' | 'CulturePnt' | 'CultureSrf' | 'FacilityPnt' | 'HydrographyCrv' | 'HydrographySrf' | 'MilitarySrf' | 'SettlementSrf' | 'StructurePnt' | 'TransportationGroundCrv' | 'UtilityInfrastructureCrv' | 'UtilityInfrastructurePnt' | 'VegetationSrf', styleId: 'Topographic' | 'Overlay' | 'Night' | 'default', f?: 'json' | 'html', pretty?: boolean, observe?: 'response', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json' | 'text/html' | 'application/problem+json' | 'text/xml'}): Observable<HttpResponse<any>>;
    public collectionsCollectionIdStylesStyleIdTilesGet(collectionId: 'AgricultureSrf' | 'CulturePnt' | 'CultureSrf' | 'FacilityPnt' | 'HydrographyCrv' | 'HydrographySrf' | 'MilitarySrf' | 'SettlementSrf' | 'StructurePnt' | 'TransportationGroundCrv' | 'UtilityInfrastructureCrv' | 'UtilityInfrastructurePnt' | 'VegetationSrf', styleId: 'Topographic' | 'Overlay' | 'Night' | 'default', f?: 'json' | 'html', pretty?: boolean, observe?: 'events', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json' | 'text/html' | 'application/problem+json' | 'text/xml'}): Observable<HttpEvent<any>>;
    public collectionsCollectionIdStylesStyleIdTilesGet(collectionId: 'AgricultureSrf' | 'CulturePnt' | 'CultureSrf' | 'FacilityPnt' | 'HydrographyCrv' | 'HydrographySrf' | 'MilitarySrf' | 'SettlementSrf' | 'StructurePnt' | 'TransportationGroundCrv' | 'UtilityInfrastructureCrv' | 'UtilityInfrastructurePnt' | 'VegetationSrf', styleId: 'Topographic' | 'Overlay' | 'Night' | 'default', f?: 'json' | 'html', pretty?: boolean, observe: any = 'body', reportProgress: boolean = false, options?: {httpHeaderAccept?: 'application/json' | 'text/html' | 'application/problem+json' | 'text/xml'}): Observable<any> {
        if (collectionId === null || collectionId === undefined) {
            throw new Error('Required parameter collectionId was null or undefined when calling collectionsCollectionIdStylesStyleIdTilesGet.');
        }
        if (styleId === null || styleId === undefined) {
            throw new Error('Required parameter styleId was null or undefined when calling collectionsCollectionIdStylesStyleIdTilesGet.');
        }

        let queryParameters = new HttpParams({encoder: this.encoder});
        if (f !== undefined && f !== null) {
          queryParameters = this.addToHttpParams(queryParameters,
            <any>f, 'f');
        }
        if (pretty !== undefined && pretty !== null) {
          queryParameters = this.addToHttpParams(queryParameters,
            <any>pretty, 'pretty');
        }

        let headers = this.defaultHeaders;

        let credential: string | undefined;
        // authentication (cwApiKeyHeader) required
        credential = this.configuration.lookupCredential('cwApiKeyHeader');
        if (credential) {
            headers = headers.set('CubeWerx-API-Key', credential);
        }

        // authentication (cwApiKeyQuery) required
        credential = this.configuration.lookupCredential('cwApiKeyQuery');
        if (credential) {
            queryParameters = queryParameters.set('apiKey', credential);
        }

        // authentication (cwAuth) required
        credential = this.configuration.lookupCredential('cwAuth');
        if (credential) {
        }

        // authentication (httpBearer) required
        credential = this.configuration.lookupCredential('httpBearer');
        if (credential) {
        }

        // authentication (oauth2) required
        credential = this.configuration.lookupCredential('oauth2');
        if (credential) {
            headers = headers.set('Authorization', 'Bearer ' + credential);
        }

        // authentication (oauth2) required
        credential = this.configuration.lookupCredential('oauth2');
        if (credential) {
            headers = headers.set('Authorization', 'Bearer ' + credential);
        }

        // authentication (oauth2) required
        credential = this.configuration.lookupCredential('oauth2');
        if (credential) {
            headers = headers.set('Authorization', 'Bearer ' + credential);
        }

        let httpHeaderAcceptSelected: string | undefined = options && options.httpHeaderAccept;
        if (httpHeaderAcceptSelected === undefined) {
            // to determine the Accept header
            const httpHeaderAccepts: string[] = [
                'application/json',
                'text/html',
                'application/problem+json',
                'text/xml'
            ];
            httpHeaderAcceptSelected = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        }
        if (httpHeaderAcceptSelected !== undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }


        let responseType: 'text' | 'json' = 'json';
        if(httpHeaderAcceptSelected && httpHeaderAcceptSelected.startsWith('text')) {
            responseType = 'text';
        }

        return this.httpClient.get<any>(`${this.configuration.basePath}/collections/${encodeURIComponent(String(collectionId))}/styles/${encodeURIComponent(String(styleId))}/tiles`,
            {
                params: queryParameters,
                responseType: <any>responseType,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * A metadata document describing the data tiles that are available for the specified collection, filtered by the scale rules and conditions of the specified style, in the specified tile-matrix set.
     * @param collectionId The identifier of a collection in this data store.
     * @param styleId The identifier of a style in this data store that\&#39;s compatible with the specified collection.
     * @param tileMatrixSetId The identifier of a tile-matrix set that this collection is available in.
     * @param f A token indicating the content type to return.  Overrides the HTTP \&quot;Accept\&quot; header if present.
     * @param pretty Whether or not the output should be pretty-formatted (with whitespace, etc.).
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public collectionsCollectionIdStylesStyleIdTilesTileMatrixSetIdGet(collectionId: 'AgricultureSrf' | 'CulturePnt' | 'CultureSrf' | 'FacilityPnt' | 'HydrographyCrv' | 'HydrographySrf' | 'MilitarySrf' | 'SettlementSrf' | 'StructurePnt' | 'TransportationGroundCrv' | 'UtilityInfrastructureCrv' | 'UtilityInfrastructurePnt' | 'VegetationSrf', styleId: 'Topographic' | 'Overlay' | 'Night' | 'default', tileMatrixSetId: 'wgs84' | '3395' | 'smerc', f?: 'json' | 'html', pretty?: boolean, observe?: 'body', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json' | 'text/html' | 'application/problem+json' | 'text/xml'}): Observable<any>;
    public collectionsCollectionIdStylesStyleIdTilesTileMatrixSetIdGet(collectionId: 'AgricultureSrf' | 'CulturePnt' | 'CultureSrf' | 'FacilityPnt' | 'HydrographyCrv' | 'HydrographySrf' | 'MilitarySrf' | 'SettlementSrf' | 'StructurePnt' | 'TransportationGroundCrv' | 'UtilityInfrastructureCrv' | 'UtilityInfrastructurePnt' | 'VegetationSrf', styleId: 'Topographic' | 'Overlay' | 'Night' | 'default', tileMatrixSetId: 'wgs84' | '3395' | 'smerc', f?: 'json' | 'html', pretty?: boolean, observe?: 'response', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json' | 'text/html' | 'application/problem+json' | 'text/xml'}): Observable<HttpResponse<any>>;
    public collectionsCollectionIdStylesStyleIdTilesTileMatrixSetIdGet(collectionId: 'AgricultureSrf' | 'CulturePnt' | 'CultureSrf' | 'FacilityPnt' | 'HydrographyCrv' | 'HydrographySrf' | 'MilitarySrf' | 'SettlementSrf' | 'StructurePnt' | 'TransportationGroundCrv' | 'UtilityInfrastructureCrv' | 'UtilityInfrastructurePnt' | 'VegetationSrf', styleId: 'Topographic' | 'Overlay' | 'Night' | 'default', tileMatrixSetId: 'wgs84' | '3395' | 'smerc', f?: 'json' | 'html', pretty?: boolean, observe?: 'events', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json' | 'text/html' | 'application/problem+json' | 'text/xml'}): Observable<HttpEvent<any>>;
    public collectionsCollectionIdStylesStyleIdTilesTileMatrixSetIdGet(collectionId: 'AgricultureSrf' | 'CulturePnt' | 'CultureSrf' | 'FacilityPnt' | 'HydrographyCrv' | 'HydrographySrf' | 'MilitarySrf' | 'SettlementSrf' | 'StructurePnt' | 'TransportationGroundCrv' | 'UtilityInfrastructureCrv' | 'UtilityInfrastructurePnt' | 'VegetationSrf', styleId: 'Topographic' | 'Overlay' | 'Night' | 'default', tileMatrixSetId: 'wgs84' | '3395' | 'smerc', f?: 'json' | 'html', pretty?: boolean, observe: any = 'body', reportProgress: boolean = false, options?: {httpHeaderAccept?: 'application/json' | 'text/html' | 'application/problem+json' | 'text/xml'}): Observable<any> {
        if (collectionId === null || collectionId === undefined) {
            throw new Error('Required parameter collectionId was null or undefined when calling collectionsCollectionIdStylesStyleIdTilesTileMatrixSetIdGet.');
        }
        if (styleId === null || styleId === undefined) {
            throw new Error('Required parameter styleId was null or undefined when calling collectionsCollectionIdStylesStyleIdTilesTileMatrixSetIdGet.');
        }
        if (tileMatrixSetId === null || tileMatrixSetId === undefined) {
            throw new Error('Required parameter tileMatrixSetId was null or undefined when calling collectionsCollectionIdStylesStyleIdTilesTileMatrixSetIdGet.');
        }

        let queryParameters = new HttpParams({encoder: this.encoder});
        if (f !== undefined && f !== null) {
          queryParameters = this.addToHttpParams(queryParameters,
            <any>f, 'f');
        }
        if (pretty !== undefined && pretty !== null) {
          queryParameters = this.addToHttpParams(queryParameters,
            <any>pretty, 'pretty');
        }

        let headers = this.defaultHeaders;

        let credential: string | undefined;
        // authentication (cwApiKeyHeader) required
        credential = this.configuration.lookupCredential('cwApiKeyHeader');
        if (credential) {
            headers = headers.set('CubeWerx-API-Key', credential);
        }

        // authentication (cwApiKeyQuery) required
        credential = this.configuration.lookupCredential('cwApiKeyQuery');
        if (credential) {
            queryParameters = queryParameters.set('apiKey', credential);
        }

        // authentication (cwAuth) required
        credential = this.configuration.lookupCredential('cwAuth');
        if (credential) {
        }

        // authentication (httpBearer) required
        credential = this.configuration.lookupCredential('httpBearer');
        if (credential) {
        }

        // authentication (oauth2) required
        credential = this.configuration.lookupCredential('oauth2');
        if (credential) {
            headers = headers.set('Authorization', 'Bearer ' + credential);
        }

        // authentication (oauth2) required
        credential = this.configuration.lookupCredential('oauth2');
        if (credential) {
            headers = headers.set('Authorization', 'Bearer ' + credential);
        }

        // authentication (oauth2) required
        credential = this.configuration.lookupCredential('oauth2');
        if (credential) {
            headers = headers.set('Authorization', 'Bearer ' + credential);
        }

        let httpHeaderAcceptSelected: string | undefined = options && options.httpHeaderAccept;
        if (httpHeaderAcceptSelected === undefined) {
            // to determine the Accept header
            const httpHeaderAccepts: string[] = [
                'application/json',
                'text/html',
                'application/problem+json',
                'text/xml'
            ];
            httpHeaderAcceptSelected = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        }
        if (httpHeaderAcceptSelected !== undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }


        let responseType: 'text' | 'json' = 'json';
        if(httpHeaderAcceptSelected && httpHeaderAcceptSelected.startsWith('text')) {
            responseType = 'text';
        }

        return this.httpClient.get<any>(`${this.configuration.basePath}/collections/${encodeURIComponent(String(collectionId))}/styles/${encodeURIComponent(String(styleId))}/tiles/${encodeURIComponent(String(tileMatrixSetId))}`,
            {
                params: queryParameters,
                responseType: <any>responseType,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * A data tile of the specified collection, filtered by the scale rules and conditions of the specified style.
     * @param collectionId The identifier of a collection in this data store.
     * @param styleId The identifier of a style in this data store that\&#39;s compatible with the specified collection.
     * @param tileMatrixSetId The identifier of a tile-matrix set that this collection is available in.
     * @param tileMatrix The identifier of a tile matrix (typically a zoom level) within the specified tile-matrix set.
     * @param tileRow The zero-based row index of the tile in the specified tile matrix.
     * @param tileCol The zero-based column index of the tile in the specified tile matrix.
     * @param datetime Either a date-time or an interval, open or closed. Date and time expressions adhere to RFC 3339.  Open intervals are expressed using double-dots.  Examples:  * A date-time: \&quot;2018-02-12T23:20:50Z\&quot; * A closed interval: \&quot;2018-02-12T00:00:00Z/2018-03-18T12:31:12Z\&quot; * Open intervals: \&quot;2018-02-12T00:00:00Z/..\&quot; or \&quot;../2018-03-18T12:31:12Z\&quot;  Only elements that have a temporal property that intersects the value of &#x60;datetime&#x60; are selected.
     * @param f A token indicating the content type to return.  Overrides the HTTP \&quot;Accept\&quot; header if present.  \&quot;mvt\&quot; and \&quot;geojson\&quot; can only be requested for feature collections.
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public collectionsCollectionIdStylesStyleIdTilesTileMatrixSetIdTileMatrixTileRowTileColGet(collectionId: 'AgricultureSrf' | 'CulturePnt' | 'CultureSrf' | 'FacilityPnt' | 'HydrographyCrv' | 'HydrographySrf' | 'MilitarySrf' | 'SettlementSrf' | 'StructurePnt' | 'TransportationGroundCrv' | 'UtilityInfrastructureCrv' | 'UtilityInfrastructurePnt' | 'VegetationSrf', styleId: 'Topographic' | 'Overlay' | 'Night' | 'default', tileMatrixSetId: 'wgs84' | '3395' | 'smerc', tileMatrix: string, tileRow: number, tileCol: number, datetime?: string, f?: 'mvt' | 'geojson', observe?: 'body', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/vnd.mapbox-vector-tile' | 'application/geo+json' | 'image/tiff' | 'application/x-cubewerx-wkb' | 'application/problem+json' | 'text/xml' | 'text/html' | 'application/json'}): Observable<any>;
    public collectionsCollectionIdStylesStyleIdTilesTileMatrixSetIdTileMatrixTileRowTileColGet(collectionId: 'AgricultureSrf' | 'CulturePnt' | 'CultureSrf' | 'FacilityPnt' | 'HydrographyCrv' | 'HydrographySrf' | 'MilitarySrf' | 'SettlementSrf' | 'StructurePnt' | 'TransportationGroundCrv' | 'UtilityInfrastructureCrv' | 'UtilityInfrastructurePnt' | 'VegetationSrf', styleId: 'Topographic' | 'Overlay' | 'Night' | 'default', tileMatrixSetId: 'wgs84' | '3395' | 'smerc', tileMatrix: string, tileRow: number, tileCol: number, datetime?: string, f?: 'mvt' | 'geojson', observe?: 'response', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/vnd.mapbox-vector-tile' | 'application/geo+json' | 'image/tiff' | 'application/x-cubewerx-wkb' | 'application/problem+json' | 'text/xml' | 'text/html' | 'application/json'}): Observable<HttpResponse<any>>;
    public collectionsCollectionIdStylesStyleIdTilesTileMatrixSetIdTileMatrixTileRowTileColGet(collectionId: 'AgricultureSrf' | 'CulturePnt' | 'CultureSrf' | 'FacilityPnt' | 'HydrographyCrv' | 'HydrographySrf' | 'MilitarySrf' | 'SettlementSrf' | 'StructurePnt' | 'TransportationGroundCrv' | 'UtilityInfrastructureCrv' | 'UtilityInfrastructurePnt' | 'VegetationSrf', styleId: 'Topographic' | 'Overlay' | 'Night' | 'default', tileMatrixSetId: 'wgs84' | '3395' | 'smerc', tileMatrix: string, tileRow: number, tileCol: number, datetime?: string, f?: 'mvt' | 'geojson', observe?: 'events', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/vnd.mapbox-vector-tile' | 'application/geo+json' | 'image/tiff' | 'application/x-cubewerx-wkb' | 'application/problem+json' | 'text/xml' | 'text/html' | 'application/json'}): Observable<HttpEvent<any>>;
    public collectionsCollectionIdStylesStyleIdTilesTileMatrixSetIdTileMatrixTileRowTileColGet(collectionId: 'AgricultureSrf' | 'CulturePnt' | 'CultureSrf' | 'FacilityPnt' | 'HydrographyCrv' | 'HydrographySrf' | 'MilitarySrf' | 'SettlementSrf' | 'StructurePnt' | 'TransportationGroundCrv' | 'UtilityInfrastructureCrv' | 'UtilityInfrastructurePnt' | 'VegetationSrf', styleId: 'Topographic' | 'Overlay' | 'Night' | 'default', tileMatrixSetId: 'wgs84' | '3395' | 'smerc', tileMatrix: string, tileRow: number, tileCol: number, datetime?: string, f?: 'mvt' | 'geojson', observe: any = 'body', reportProgress: boolean = false, options?: {httpHeaderAccept?: 'application/vnd.mapbox-vector-tile' | 'application/geo+json' | 'image/tiff' | 'application/x-cubewerx-wkb' | 'application/problem+json' | 'text/xml' | 'text/html' | 'application/json'}): Observable<any> {
        if (collectionId === null || collectionId === undefined) {
            throw new Error('Required parameter collectionId was null or undefined when calling collectionsCollectionIdStylesStyleIdTilesTileMatrixSetIdTileMatrixTileRowTileColGet.');
        }
        if (styleId === null || styleId === undefined) {
            throw new Error('Required parameter styleId was null or undefined when calling collectionsCollectionIdStylesStyleIdTilesTileMatrixSetIdTileMatrixTileRowTileColGet.');
        }
        if (tileMatrixSetId === null || tileMatrixSetId === undefined) {
            throw new Error('Required parameter tileMatrixSetId was null or undefined when calling collectionsCollectionIdStylesStyleIdTilesTileMatrixSetIdTileMatrixTileRowTileColGet.');
        }
        if (tileMatrix === null || tileMatrix === undefined) {
            throw new Error('Required parameter tileMatrix was null or undefined when calling collectionsCollectionIdStylesStyleIdTilesTileMatrixSetIdTileMatrixTileRowTileColGet.');
        }
        if (tileRow === null || tileRow === undefined) {
            throw new Error('Required parameter tileRow was null or undefined when calling collectionsCollectionIdStylesStyleIdTilesTileMatrixSetIdTileMatrixTileRowTileColGet.');
        }
        if (tileCol === null || tileCol === undefined) {
            throw new Error('Required parameter tileCol was null or undefined when calling collectionsCollectionIdStylesStyleIdTilesTileMatrixSetIdTileMatrixTileRowTileColGet.');
        }

        let queryParameters = new HttpParams({encoder: this.encoder});
        if (datetime !== undefined && datetime !== null) {
          queryParameters = this.addToHttpParams(queryParameters,
            <any>datetime, 'datetime');
        }
        if (f !== undefined && f !== null) {
          queryParameters = this.addToHttpParams(queryParameters,
            <any>f, 'f');
        }

        let headers = this.defaultHeaders;

        let credential: string | undefined;
        // authentication (cwApiKeyHeader) required
        credential = this.configuration.lookupCredential('cwApiKeyHeader');
        if (credential) {
            headers = headers.set('CubeWerx-API-Key', credential);
        }

        // authentication (cwApiKeyQuery) required
        credential = this.configuration.lookupCredential('cwApiKeyQuery');
        if (credential) {
            queryParameters = queryParameters.set('apiKey', credential);
        }

        // authentication (cwAuth) required
        credential = this.configuration.lookupCredential('cwAuth');
        if (credential) {
        }

        // authentication (httpBearer) required
        credential = this.configuration.lookupCredential('httpBearer');
        if (credential) {
        }

        // authentication (oauth2) required
        credential = this.configuration.lookupCredential('oauth2');
        if (credential) {
            headers = headers.set('Authorization', 'Bearer ' + credential);
        }

        // authentication (oauth2) required
        credential = this.configuration.lookupCredential('oauth2');
        if (credential) {
            headers = headers.set('Authorization', 'Bearer ' + credential);
        }

        // authentication (oauth2) required
        credential = this.configuration.lookupCredential('oauth2');
        if (credential) {
            headers = headers.set('Authorization', 'Bearer ' + credential);
        }

        let httpHeaderAcceptSelected: string | undefined = options && options.httpHeaderAccept;
        if (httpHeaderAcceptSelected === undefined) {
            // to determine the Accept header
            const httpHeaderAccepts: string[] = [
                'application/vnd.mapbox-vector-tile',
                'application/geo+json',
                'image/tiff',
                'application/x-cubewerx-wkb',
                'application/problem+json',
                'text/xml',
                'text/html',
                'application/json'
            ];
            httpHeaderAcceptSelected = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        }
        if (httpHeaderAcceptSelected !== undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }


        let responseType: 'text' | 'json' = 'json';
        if(httpHeaderAcceptSelected && httpHeaderAcceptSelected.startsWith('text')) {
            responseType = 'text';
        }

        return this.httpClient.get<any>(`${this.configuration.basePath}/collections/${encodeURIComponent(String(collectionId))}/styles/${encodeURIComponent(String(styleId))}/tiles/${encodeURIComponent(String(tileMatrixSetId))}/${encodeURIComponent(String(tileMatrix))}/${encodeURIComponent(String(tileRow))}/${encodeURIComponent(String(tileCol))}`,
            {
                params: queryParameters,
                responseType: <any>responseType,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * A metadata document describing the data tilesets that are available for the specified collection.
     * @param collectionId The identifier of a collection in this data store.
     * @param f A token indicating the content type to return.  Overrides the HTTP \&quot;Accept\&quot; header if present.
     * @param pretty Whether or not the output should be pretty-formatted (with whitespace, etc.).
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public collectionsCollectionIdTilesGet(collectionId: 'AgricultureSrf' | 'CulturePnt' | 'CultureSrf' | 'Daraa_DTED' | 'Daraa_mosaic_2019' | 'FacilityPnt' | 'HydrographyCrv' | 'HydrographySrf' | 'MilitarySrf' | 'SettlementSrf' | 'StructurePnt' | 'TransportationGroundCrv' | 'UtilityInfrastructureCrv' | 'UtilityInfrastructurePnt' | 'VegetationSrf', f?: 'json' | 'html', pretty?: boolean, observe?: 'body', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json' | 'text/html' | 'application/problem+json' | 'text/xml'}): Observable<any>;
    public collectionsCollectionIdTilesGet(collectionId: 'AgricultureSrf' | 'CulturePnt' | 'CultureSrf' | 'Daraa_DTED' | 'Daraa_mosaic_2019' | 'FacilityPnt' | 'HydrographyCrv' | 'HydrographySrf' | 'MilitarySrf' | 'SettlementSrf' | 'StructurePnt' | 'TransportationGroundCrv' | 'UtilityInfrastructureCrv' | 'UtilityInfrastructurePnt' | 'VegetationSrf', f?: 'json' | 'html', pretty?: boolean, observe?: 'response', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json' | 'text/html' | 'application/problem+json' | 'text/xml'}): Observable<HttpResponse<any>>;
    public collectionsCollectionIdTilesGet(collectionId: 'AgricultureSrf' | 'CulturePnt' | 'CultureSrf' | 'Daraa_DTED' | 'Daraa_mosaic_2019' | 'FacilityPnt' | 'HydrographyCrv' | 'HydrographySrf' | 'MilitarySrf' | 'SettlementSrf' | 'StructurePnt' | 'TransportationGroundCrv' | 'UtilityInfrastructureCrv' | 'UtilityInfrastructurePnt' | 'VegetationSrf', f?: 'json' | 'html', pretty?: boolean, observe?: 'events', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json' | 'text/html' | 'application/problem+json' | 'text/xml'}): Observable<HttpEvent<any>>;
    public collectionsCollectionIdTilesGet(collectionId: 'AgricultureSrf' | 'CulturePnt' | 'CultureSrf' | 'Daraa_DTED' | 'Daraa_mosaic_2019' | 'FacilityPnt' | 'HydrographyCrv' | 'HydrographySrf' | 'MilitarySrf' | 'SettlementSrf' | 'StructurePnt' | 'TransportationGroundCrv' | 'UtilityInfrastructureCrv' | 'UtilityInfrastructurePnt' | 'VegetationSrf', f?: 'json' | 'html', pretty?: boolean, observe: any = 'body', reportProgress: boolean = false, options?: {httpHeaderAccept?: 'application/json' | 'text/html' | 'application/problem+json' | 'text/xml'}): Observable<any> {
        if (collectionId === null || collectionId === undefined) {
            throw new Error('Required parameter collectionId was null or undefined when calling collectionsCollectionIdTilesGet.');
        }

        let queryParameters = new HttpParams({encoder: this.encoder});
        if (f !== undefined && f !== null) {
          queryParameters = this.addToHttpParams(queryParameters,
            <any>f, 'f');
        }
        if (pretty !== undefined && pretty !== null) {
          queryParameters = this.addToHttpParams(queryParameters,
            <any>pretty, 'pretty');
        }

        let headers = this.defaultHeaders;

        let credential: string | undefined;
        // authentication (cwApiKeyHeader) required
        credential = this.configuration.lookupCredential('cwApiKeyHeader');
        if (credential) {
            headers = headers.set('CubeWerx-API-Key', credential);
        }

        // authentication (cwApiKeyQuery) required
        credential = this.configuration.lookupCredential('cwApiKeyQuery');
        if (credential) {
            queryParameters = queryParameters.set('apiKey', credential);
        }

        // authentication (cwAuth) required
        credential = this.configuration.lookupCredential('cwAuth');
        if (credential) {
        }

        // authentication (httpBearer) required
        credential = this.configuration.lookupCredential('httpBearer');
        if (credential) {
        }

        // authentication (oauth2) required
        credential = this.configuration.lookupCredential('oauth2');
        if (credential) {
            headers = headers.set('Authorization', 'Bearer ' + credential);
        }

        // authentication (oauth2) required
        credential = this.configuration.lookupCredential('oauth2');
        if (credential) {
            headers = headers.set('Authorization', 'Bearer ' + credential);
        }

        // authentication (oauth2) required
        credential = this.configuration.lookupCredential('oauth2');
        if (credential) {
            headers = headers.set('Authorization', 'Bearer ' + credential);
        }

        let httpHeaderAcceptSelected: string | undefined = options && options.httpHeaderAccept;
        if (httpHeaderAcceptSelected === undefined) {
            // to determine the Accept header
            const httpHeaderAccepts: string[] = [
                'application/json',
                'text/html',
                'application/problem+json',
                'text/xml'
            ];
            httpHeaderAcceptSelected = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        }
        if (httpHeaderAcceptSelected !== undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }


        let responseType: 'text' | 'json' = 'json';
        if(httpHeaderAcceptSelected && httpHeaderAcceptSelected.startsWith('text')) {
            responseType = 'text';
        }

        return this.httpClient.get<any>(`${this.configuration.basePath}/collections/${encodeURIComponent(String(collectionId))}/tiles`,
            {
                params: queryParameters,
                responseType: <any>responseType,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * A metadata document describing the data tiles that are available for the specified collection in the specified tile-matrix set.
     * @param collectionId The identifier of a collection in this data store.
     * @param tileMatrixSetId The identifier of a tile-matrix set that this collection is available in.
     * @param f A token indicating the content type to return.  Overrides the HTTP \&quot;Accept\&quot; header if present.
     * @param pretty Whether or not the output should be pretty-formatted (with whitespace, etc.).
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public collectionsCollectionIdTilesTileMatrixSetIdGet(collectionId: 'AgricultureSrf' | 'CulturePnt' | 'CultureSrf' | 'Daraa_DTED' | 'Daraa_mosaic_2019' | 'FacilityPnt' | 'HydrographyCrv' | 'HydrographySrf' | 'MilitarySrf' | 'SettlementSrf' | 'StructurePnt' | 'TransportationGroundCrv' | 'UtilityInfrastructureCrv' | 'UtilityInfrastructurePnt' | 'VegetationSrf', tileMatrixSetId: 'wgs84' | '3395' | 'smerc', f?: 'json' | 'html', pretty?: boolean, observe?: 'body', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json' | 'text/html' | 'application/problem+json' | 'text/xml'}): Observable<any>;
    public collectionsCollectionIdTilesTileMatrixSetIdGet(collectionId: 'AgricultureSrf' | 'CulturePnt' | 'CultureSrf' | 'Daraa_DTED' | 'Daraa_mosaic_2019' | 'FacilityPnt' | 'HydrographyCrv' | 'HydrographySrf' | 'MilitarySrf' | 'SettlementSrf' | 'StructurePnt' | 'TransportationGroundCrv' | 'UtilityInfrastructureCrv' | 'UtilityInfrastructurePnt' | 'VegetationSrf', tileMatrixSetId: 'wgs84' | '3395' | 'smerc', f?: 'json' | 'html', pretty?: boolean, observe?: 'response', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json' | 'text/html' | 'application/problem+json' | 'text/xml'}): Observable<HttpResponse<any>>;
    public collectionsCollectionIdTilesTileMatrixSetIdGet(collectionId: 'AgricultureSrf' | 'CulturePnt' | 'CultureSrf' | 'Daraa_DTED' | 'Daraa_mosaic_2019' | 'FacilityPnt' | 'HydrographyCrv' | 'HydrographySrf' | 'MilitarySrf' | 'SettlementSrf' | 'StructurePnt' | 'TransportationGroundCrv' | 'UtilityInfrastructureCrv' | 'UtilityInfrastructurePnt' | 'VegetationSrf', tileMatrixSetId: 'wgs84' | '3395' | 'smerc', f?: 'json' | 'html', pretty?: boolean, observe?: 'events', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json' | 'text/html' | 'application/problem+json' | 'text/xml'}): Observable<HttpEvent<any>>;
    public collectionsCollectionIdTilesTileMatrixSetIdGet(collectionId: 'AgricultureSrf' | 'CulturePnt' | 'CultureSrf' | 'Daraa_DTED' | 'Daraa_mosaic_2019' | 'FacilityPnt' | 'HydrographyCrv' | 'HydrographySrf' | 'MilitarySrf' | 'SettlementSrf' | 'StructurePnt' | 'TransportationGroundCrv' | 'UtilityInfrastructureCrv' | 'UtilityInfrastructurePnt' | 'VegetationSrf', tileMatrixSetId: 'wgs84' | '3395' | 'smerc', f?: 'json' | 'html', pretty?: boolean, observe: any = 'body', reportProgress: boolean = false, options?: {httpHeaderAccept?: 'application/json' | 'text/html' | 'application/problem+json' | 'text/xml'}): Observable<any> {
        if (collectionId === null || collectionId === undefined) {
            throw new Error('Required parameter collectionId was null or undefined when calling collectionsCollectionIdTilesTileMatrixSetIdGet.');
        }
        if (tileMatrixSetId === null || tileMatrixSetId === undefined) {
            throw new Error('Required parameter tileMatrixSetId was null or undefined when calling collectionsCollectionIdTilesTileMatrixSetIdGet.');
        }

        let queryParameters = new HttpParams({encoder: this.encoder});
        if (f !== undefined && f !== null) {
          queryParameters = this.addToHttpParams(queryParameters,
            <any>f, 'f');
        }
        if (pretty !== undefined && pretty !== null) {
          queryParameters = this.addToHttpParams(queryParameters,
            <any>pretty, 'pretty');
        }

        let headers = this.defaultHeaders;

        let credential: string | undefined;
        // authentication (cwApiKeyHeader) required
        credential = this.configuration.lookupCredential('cwApiKeyHeader');
        if (credential) {
            headers = headers.set('CubeWerx-API-Key', credential);
        }

        // authentication (cwApiKeyQuery) required
        credential = this.configuration.lookupCredential('cwApiKeyQuery');
        if (credential) {
            queryParameters = queryParameters.set('apiKey', credential);
        }

        // authentication (cwAuth) required
        credential = this.configuration.lookupCredential('cwAuth');
        if (credential) {
        }

        // authentication (httpBearer) required
        credential = this.configuration.lookupCredential('httpBearer');
        if (credential) {
        }

        // authentication (oauth2) required
        credential = this.configuration.lookupCredential('oauth2');
        if (credential) {
            headers = headers.set('Authorization', 'Bearer ' + credential);
        }

        // authentication (oauth2) required
        credential = this.configuration.lookupCredential('oauth2');
        if (credential) {
            headers = headers.set('Authorization', 'Bearer ' + credential);
        }

        // authentication (oauth2) required
        credential = this.configuration.lookupCredential('oauth2');
        if (credential) {
            headers = headers.set('Authorization', 'Bearer ' + credential);
        }

        let httpHeaderAcceptSelected: string | undefined = options && options.httpHeaderAccept;
        if (httpHeaderAcceptSelected === undefined) {
            // to determine the Accept header
            const httpHeaderAccepts: string[] = [
                'application/json',
                'text/html',
                'application/problem+json',
                'text/xml'
            ];
            httpHeaderAcceptSelected = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        }
        if (httpHeaderAcceptSelected !== undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }


        let responseType: 'text' | 'json' = 'json';
        if(httpHeaderAcceptSelected && httpHeaderAcceptSelected.startsWith('text')) {
            responseType = 'text';
        }

        return this.httpClient.get<any>(`${this.configuration.basePath}/collections/${encodeURIComponent(String(collectionId))}/tiles/${encodeURIComponent(String(tileMatrixSetId))}`,
            {
                params: queryParameters,
                responseType: <any>responseType,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * A data tile of the specified collection.
     * @param collectionId The identifier of a collection in this data store.
     * @param tileMatrixSetId The identifier of a tile-matrix set that this collection is available in.
     * @param tileMatrix The identifier of a tile matrix (typically a zoom level) within the specified tile-matrix set.
     * @param tileRow The zero-based row index of the tile in the specified tile matrix.
     * @param tileCol The zero-based column index of the tile in the specified tile matrix.
     * @param datetime Either a date-time or an interval, open or closed. Date and time expressions adhere to RFC 3339.  Open intervals are expressed using double-dots.  Examples:  * A date-time: \&quot;2018-02-12T23:20:50Z\&quot; * A closed interval: \&quot;2018-02-12T00:00:00Z/2018-03-18T12:31:12Z\&quot; * Open intervals: \&quot;2018-02-12T00:00:00Z/..\&quot; or \&quot;../2018-03-18T12:31:12Z\&quot;  Only elements that have a temporal property that intersects the value of &#x60;datetime&#x60; are selected.
     * @param f A token indicating the content type to return.  Overrides the HTTP \&quot;Accept\&quot; header if present.  A value of \&quot;wkb\&quot; (content type \&quot;application/x-cubewerx-wkb\&quot;) indicates CubeWerx\&#39;s raster extension to the Well-Known-Binary format.  \&quot;mvt\&quot; and \&quot;geojson\&quot; can only be requested for feature collections, and \&quot;tiff\&quot; and \&quot;wkb\&quot; can only be requested for coverage collections.
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public collectionsCollectionIdTilesTileMatrixSetIdTileMatrixTileRowTileColGet(collectionId: 'AgricultureSrf' | 'CulturePnt' | 'CultureSrf' | 'Daraa_DTED' | 'Daraa_mosaic_2019' | 'FacilityPnt' | 'HydrographyCrv' | 'HydrographySrf' | 'MilitarySrf' | 'SettlementSrf' | 'StructurePnt' | 'TransportationGroundCrv' | 'UtilityInfrastructureCrv' | 'UtilityInfrastructurePnt' | 'VegetationSrf', tileMatrixSetId: 'wgs84' | '3395' | 'smerc', tileMatrix: string, tileRow: number, tileCol: number, datetime?: string, f?: 'mvt' | 'geojson' | 'tiff' | 'wkb', observe?: 'body', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/vnd.mapbox-vector-tile' | 'application/geo+json' | 'image/tiff' | 'application/x-cubewerx-wkb' | 'application/problem+json' | 'text/xml' | 'text/html' | 'application/json'}): Observable<any>;
    public collectionsCollectionIdTilesTileMatrixSetIdTileMatrixTileRowTileColGet(collectionId: 'AgricultureSrf' | 'CulturePnt' | 'CultureSrf' | 'Daraa_DTED' | 'Daraa_mosaic_2019' | 'FacilityPnt' | 'HydrographyCrv' | 'HydrographySrf' | 'MilitarySrf' | 'SettlementSrf' | 'StructurePnt' | 'TransportationGroundCrv' | 'UtilityInfrastructureCrv' | 'UtilityInfrastructurePnt' | 'VegetationSrf', tileMatrixSetId: 'wgs84' | '3395' | 'smerc', tileMatrix: string, tileRow: number, tileCol: number, datetime?: string, f?: 'mvt' | 'geojson' | 'tiff' | 'wkb', observe?: 'response', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/vnd.mapbox-vector-tile' | 'application/geo+json' | 'image/tiff' | 'application/x-cubewerx-wkb' | 'application/problem+json' | 'text/xml' | 'text/html' | 'application/json'}): Observable<HttpResponse<any>>;
    public collectionsCollectionIdTilesTileMatrixSetIdTileMatrixTileRowTileColGet(collectionId: 'AgricultureSrf' | 'CulturePnt' | 'CultureSrf' | 'Daraa_DTED' | 'Daraa_mosaic_2019' | 'FacilityPnt' | 'HydrographyCrv' | 'HydrographySrf' | 'MilitarySrf' | 'SettlementSrf' | 'StructurePnt' | 'TransportationGroundCrv' | 'UtilityInfrastructureCrv' | 'UtilityInfrastructurePnt' | 'VegetationSrf', tileMatrixSetId: 'wgs84' | '3395' | 'smerc', tileMatrix: string, tileRow: number, tileCol: number, datetime?: string, f?: 'mvt' | 'geojson' | 'tiff' | 'wkb', observe?: 'events', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/vnd.mapbox-vector-tile' | 'application/geo+json' | 'image/tiff' | 'application/x-cubewerx-wkb' | 'application/problem+json' | 'text/xml' | 'text/html' | 'application/json'}): Observable<HttpEvent<any>>;
    public collectionsCollectionIdTilesTileMatrixSetIdTileMatrixTileRowTileColGet(collectionId: 'AgricultureSrf' | 'CulturePnt' | 'CultureSrf' | 'Daraa_DTED' | 'Daraa_mosaic_2019' | 'FacilityPnt' | 'HydrographyCrv' | 'HydrographySrf' | 'MilitarySrf' | 'SettlementSrf' | 'StructurePnt' | 'TransportationGroundCrv' | 'UtilityInfrastructureCrv' | 'UtilityInfrastructurePnt' | 'VegetationSrf', tileMatrixSetId: 'wgs84' | '3395' | 'smerc', tileMatrix: string, tileRow: number, tileCol: number, datetime?: string, f?: 'mvt' | 'geojson' | 'tiff' | 'wkb', observe: any = 'body', reportProgress: boolean = false, options?: {httpHeaderAccept?: 'application/vnd.mapbox-vector-tile' | 'application/geo+json' | 'image/tiff' | 'application/x-cubewerx-wkb' | 'application/problem+json' | 'text/xml' | 'text/html' | 'application/json'}): Observable<any> {
        if (collectionId === null || collectionId === undefined) {
            throw new Error('Required parameter collectionId was null or undefined when calling collectionsCollectionIdTilesTileMatrixSetIdTileMatrixTileRowTileColGet.');
        }
        if (tileMatrixSetId === null || tileMatrixSetId === undefined) {
            throw new Error('Required parameter tileMatrixSetId was null or undefined when calling collectionsCollectionIdTilesTileMatrixSetIdTileMatrixTileRowTileColGet.');
        }
        if (tileMatrix === null || tileMatrix === undefined) {
            throw new Error('Required parameter tileMatrix was null or undefined when calling collectionsCollectionIdTilesTileMatrixSetIdTileMatrixTileRowTileColGet.');
        }
        if (tileRow === null || tileRow === undefined) {
            throw new Error('Required parameter tileRow was null or undefined when calling collectionsCollectionIdTilesTileMatrixSetIdTileMatrixTileRowTileColGet.');
        }
        if (tileCol === null || tileCol === undefined) {
            throw new Error('Required parameter tileCol was null or undefined when calling collectionsCollectionIdTilesTileMatrixSetIdTileMatrixTileRowTileColGet.');
        }

        let queryParameters = new HttpParams({encoder: this.encoder});
        if (datetime !== undefined && datetime !== null) {
          queryParameters = this.addToHttpParams(queryParameters,
            <any>datetime, 'datetime');
        }
        if (f !== undefined && f !== null) {
          queryParameters = this.addToHttpParams(queryParameters,
            <any>f, 'f');
        }

        let headers = this.defaultHeaders;

        let credential: string | undefined;
        // authentication (cwApiKeyHeader) required
        credential = this.configuration.lookupCredential('cwApiKeyHeader');
        if (credential) {
            headers = headers.set('CubeWerx-API-Key', credential);
        }

        // authentication (cwApiKeyQuery) required
        credential = this.configuration.lookupCredential('cwApiKeyQuery');
        if (credential) {
            queryParameters = queryParameters.set('apiKey', credential);
        }

        // authentication (cwAuth) required
        credential = this.configuration.lookupCredential('cwAuth');
        if (credential) {
        }

        // authentication (httpBearer) required
        credential = this.configuration.lookupCredential('httpBearer');
        if (credential) {
        }

        // authentication (oauth2) required
        credential = this.configuration.lookupCredential('oauth2');
        if (credential) {
            headers = headers.set('Authorization', 'Bearer ' + credential);
        }

        // authentication (oauth2) required
        credential = this.configuration.lookupCredential('oauth2');
        if (credential) {
            headers = headers.set('Authorization', 'Bearer ' + credential);
        }

        // authentication (oauth2) required
        credential = this.configuration.lookupCredential('oauth2');
        if (credential) {
            headers = headers.set('Authorization', 'Bearer ' + credential);
        }

        let httpHeaderAcceptSelected: string | undefined = options && options.httpHeaderAccept;
        if (httpHeaderAcceptSelected === undefined) {
            // to determine the Accept header
            const httpHeaderAccepts: string[] = [
                'application/vnd.mapbox-vector-tile',
                'application/geo+json',
                'image/tiff',
                'application/x-cubewerx-wkb',
                'application/problem+json',
                'text/xml',
                'text/html',
                'application/json'
            ];
            httpHeaderAcceptSelected = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        }
        if (httpHeaderAcceptSelected !== undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }


        let responseType: 'text' | 'json' = 'json';
        if(httpHeaderAcceptSelected && httpHeaderAcceptSelected.startsWith('text')) {
            responseType = 'text';
        }

        return this.httpClient.get<any>(`${this.configuration.basePath}/collections/${encodeURIComponent(String(collectionId))}/tiles/${encodeURIComponent(String(tileMatrixSetId))}/${encodeURIComponent(String(tileMatrix))}/${encodeURIComponent(String(tileRow))}/${encodeURIComponent(String(tileCol))}`,
            {
                params: queryParameters,
                responseType: <any>responseType,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

}
