/**
 * Environmental Data Retrieval API\'s
 * Example of Candidate Environmental Data Retrieval API OpenAPI docs
 *
 * The version of the OpenAPI document: 0.0.10
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Composite Axis where the Axes values are described as Tuples rather than individual arrays
 */
export interface CompositeAxes { 
    dataType: string;
    coordinates: Array<string>;
    values: Array<Array<number | string>>;
}

