/**
 * Environmental Data Retrieval API\'s
 * Example of Candidate Environmental Data Retrieval API OpenAPI docs
 *
 * The version of the OpenAPI document: 0.0.10
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Properties to describe existing EDR features -- may be real-world or virtual sampling features.
 */
export interface EdrProperties { 
    /**
     * Either a date-time or a period string that adheres to RFC 3339. Indicates the time instant or period for which data are available from the EDR feature.
     */
    datetime: string;
    /**
     * Unique IDs of available parameters, this is the value used for querying the data and corresponds to an ID in the parameter metadata of the collection.
     */
    parameter_name: Array<string>;
    /**
     * A label such as a site name or other text to use on a link.
     */
    label: string;
    /**
     * A URI identifying the query end point. May identify a specific location.
     */
    edrqueryendpoint: string;
}

