/**
 * Environmental Data Retrieval API\'s
 * Example of Candidate Environmental Data Retrieval API OpenAPI docs
 *
 * The version of the OpenAPI document: 0.0.10
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { MultipolygonGeoJSON } from './multipolygonGeoJSON';
import { GeometrycollectionGeoJSON } from './geometrycollectionGeoJSON';
import { MultilinestringGeoJSON } from './multilinestringGeoJSON';
import { MultipointGeoJSON } from './multipointGeoJSON';
import { PointGeoJSON } from './pointGeoJSON';
import { EdrProperties } from './edrProperties';
import { PolygonGeoJSON } from './polygonGeoJSON';
import { LinestringGeoJSON } from './linestringGeoJSON';
import { Link } from './link';


export interface FeatureGeoJSON { 
    type: FeatureGeoJSON.TypeEnum;
    geometry: PointGeoJSON | MultipointGeoJSON | LinestringGeoJSON | MultilinestringGeoJSON | PolygonGeoJSON | MultipolygonGeoJSON | GeometrycollectionGeoJSON;
    properties: EdrProperties;
    id?: string | number;
    links?: Array<Link>;
}
export namespace FeatureGeoJSON {
    export type TypeEnum = 'Feature';
    export const TypeEnum = {
        Feature: 'Feature' as TypeEnum
    };
}
