/**
 * Environmental Data Retrieval API\'s
 * Example of Candidate Environmental Data Retrieval API OpenAPI docs
 *
 * The version of the OpenAPI document: 0.0.10
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface LandingPageContact { 
    /**
     * Email address of service provider
     */
    email?: string;
    /**
     * Phone number of service provider
     */
    phone?: string;
    /**
     * Fax number of service provider
     */
    fax?: string;
    hours?: string;
    instructions?: string;
    address?: string;
    postalCode?: string;
    city?: string;
    stateorprovince?: string;
    country?: string;
}

