/**
 * Environmental Data Retrieval API\'s
 * Example of Candidate Environmental Data Retrieval API OpenAPI docs
 *
 * The version of the OpenAPI document: 0.0.10
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface LinestringGeoJSON { 
    type: LinestringGeoJSON.TypeEnum;
    coordinates: Array<Array<Array<number>>>;
}
export namespace LinestringGeoJSON {
    export type TypeEnum = 'LineString' | 'LineStringM' | 'LineStringZ' | 'LineStringZM';
    export const TypeEnum = {
        LineString: 'LineString' as TypeEnum,
        LineStringM: 'LineStringM' as TypeEnum,
        LineStringZ: 'LineStringZ' as TypeEnum,
        LineStringZm: 'LineStringZM' as TypeEnum
    };
}


