/**
 * Environmental Data Retrieval API\'s
 * Example of Candidate Environmental Data Retrieval API OpenAPI docs
 *
 * The version of the OpenAPI document: 0.0.10
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface MultipolygonGeoJSON { 
    type: MultipolygonGeoJSON.TypeEnum;
    coordinates: Array<Array<Array<Array<number>>>>;
}
export namespace MultipolygonGeoJSON {
    export type TypeEnum = 'MultiPolygon';
    export const TypeEnum = {
        MultiPolygon: 'MultiPolygon' as TypeEnum
    };
}


