/**
 * Environmental Data Retrieval API\'s
 * Example of Candidate Environmental Data Retrieval API OpenAPI docs
 *
 * The version of the OpenAPI document: 0.0.10
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface CrsObject { 
    /**
     * name of the coordinate reference system, used as the value in the crs query parameter to define the required output CRS
     */
    crs: string;
    /**
     * Well Known text description of the coordinate reference system
     */
    wkt: string;
}

