/**
 * Environmental Data Retrieval API\'s
 * Example of Candidate Environmental Data Retrieval API OpenAPI docs
 *
 * The version of the OpenAPI document: 0.0.10
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * The vertical extent of the information in the collection.
 */
export interface ExtentVertical { 
    /**
     * One or more height intervals that describe the vertical extent of the dataset. The value `null` is supported and indicates an open vertical interval. In the Core only a single time interval is supported. Extensions may support multiple intervals. If multiple intervals are provided, the union of the intervals describes the vertical extent.
     */
    interval: Array<Array<string>>;
    /**
     * Coordinate reference system of the coordinates in the vertical extent (property `interval`). 
     */
    vrs: string;
    /**
     * Name of the vertical coordinate reference system
     */
    name?: string;
}

