/**
 * Environmental Data Retrieval API\'s
 * Example of Candidate Environmental Data Retrieval API OpenAPI docs
 *
 * The version of the OpenAPI document: 0.0.10
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { DataQuery } from './dataQuery';


export interface Link { 
    href: string;
    rel: string;
    type?: string;
    hreflang?: string;
    title?: string;
    length?: number;
    /**
     * defines if the link href value is a template with values requiring replacement
     */
    templated?: boolean;
    variables?: DataQuery;
}

