/**
 * Environmental Data Retrieval API\'s
 * Example of Candidate Environmental Data Retrieval API OpenAPI docs
 *
 * The version of the OpenAPI document: 0.0.10
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface MultipointGeoJSON { 
    type: MultipointGeoJSON.TypeEnum;
    coordinates: Array<Array<number>>;
}
export namespace MultipointGeoJSON {
    export type TypeEnum = 'MultiPoint';
    export const TypeEnum = {
        MultiPoint: 'MultiPoint' as TypeEnum
    };
}


