/**
 * Environmental Data Retrieval API\'s
 * Example of Candidate Environmental Data Retrieval API OpenAPI docs
 *
 * The version of the OpenAPI document: 0.0.10
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ObservedPropertyCategories } from './observedPropertyCategories';


/**
 * Description of the property
 */
export interface ObservedProperty { 
    /**
     * URI linking to an external registry which contains the definitive definition of the observed property
     */
    id?: string;
    label: string;
    description?: string;
    categories?: Array<ObservedPropertyCategories>;
}

